---
name: CI
on: push
jobs:
 clang-format:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@master
     - uses: docker://lucteo/action-cxx-toolkit:latest
       with:
         checks: clang-format
         clangformatdirs: src test_package/src
