---
name: CI
on: push
jobs:
  gcc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: docker://lucteo/action-cxx-toolkit.v9.main:latest
        with:
          checks: build test install warnings
          cc: gcc
  clang:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: docker://lucteo/action-cxx-toolkit.v9.main:latest
        with:
          checks: build test
          cc: clang-13
  clang-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: docker://lucteo/action-cxx-toolkit.v9.main:latest
        with:
          checks: clang-format
          clangformatdirs: src test_package/src
  static-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: docker://lucteo/action-cxx-toolkit.v9.main:latest
        with:
          checks: cppcheck clang-tidy
          clangtidyflags: '-quiet'
          cppcheckflags: '--enable=warning,style,performance,portability --inline-suppr'
  conan-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: docker://lucteo/action-cxx-toolkit.v9.main:latest
        with:
          checks: build
          build_command: 'conan profile detect && conan create /github/workspace/'
